name: MyAppSupaBase
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
